// <auto-generated />
using System;
using EcommerceDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("EcommerceDemo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "fa-engine",
                            Nombre = "Motor"
                        },
                        new
                        {
                            Id = 2,
                            Icono = "fa-circle-stop",
                            Nombre = "Frenos"
                        },
                        new
                        {
                            Id = 3,
                            Icono = "fa-car-side",
                            Nombre = "Suspensión"
                        },
                        new
                        {
                            Id = 4,
                            Icono = "fa-bolt",
                            Nombre = "Eléctrico"
                        },
                        new
                        {
                            Id = 5,
                            Icono = "fa-filter",
                            Nombre = "Filtros"
                        },
                        new
                        {
                            Id = 6,
                            Icono = "fa-gears",
                            Nombre = "Transmisión"
                        });
                });

            modelBuilder.Entity("EcommerceDemo.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteDireccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("EcommerceDemo.Models.OrdenItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoSKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrdenItems");
                });

            modelBuilder.Entity("EcommerceDemo.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompatibilidadAutos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Destacado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            CompatibilidadAutos = "Toyota Corolla 2015-2023, Honda Civic 2014-2022, Nissan Sentra 2016-2023",
                            Descripcion = "Filtro de aceite de alta eficiencia para motores gasolina y diésel. Compatible con múltiples marcas.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/filtro-aceite.png",
                            Marca = "Bosch",
                            Nombre = "Filtro de Aceite Bosch",
                            Precio = 8.50m,
                            SKU = "BOC-FIL-001",
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            CompatibilidadAutos = "Toyota Camry 2012-2023, Chevrolet Aveo 2011-2021, Hyundai Elantra 2013-2023",
                            Descripcion = "Bujía de iridio de larga duración con electrodo ultrafino para máxima eficiencia de combustión.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/bujia.png",
                            Marca = "NGK",
                            Nombre = "Bujía NGK Iridium IX",
                            Precio = 12.75m,
                            SKU = "NGK-BUJ-002",
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            CompatibilidadAutos = "Volkswagen Jetta 2011-2019, Audi A3 2013-2020",
                            Descripcion = "Correa de distribución reforzada con fibra de vidrio. Resistente al calor y al aceite.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/correa.png",
                            Marca = "Gates",
                            Nombre = "Correa de Distribución Gates",
                            Precio = 45.00m,
                            SKU = "GAT-COR-003",
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 1,
                            CompatibilidadAutos = "Universal - todos los vehículos a gasolina",
                            Descripcion = "Aceite de motor sintético completo para protección extrema y rendimiento máximo.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/aceite.png",
                            Marca = "Mobil 1",
                            Nombre = "Aceite Motor Mobil 1 5W-30 1L",
                            Precio = 18.90m,
                            SKU = "MOB-ACE-004",
                            Stock = 300
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 2,
                            CompatibilidadAutos = "Toyota Corolla 2014-2023, Honda Civic 2016-2023, Mazda 3 2014-2023",
                            Descripcion = "Pastillas de freno de alto rendimiento con baja emisión de polvo y nula chirriación.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/pastillas.png",
                            Marca = "Brembo",
                            Nombre = "Pastillas de Freno Brembo Delanteras",
                            Precio = 35.00m,
                            SKU = "BRE-PAS-005",
                            Stock = 80
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 2,
                            CompatibilidadAutos = "Chevrolet Cruze 2011-2019, Kia Sportage 2011-2021",
                            Descripcion = "Disco de freno ventilado de alta performance con ranuras para mejor disipación de calor.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/disco.png",
                            Marca = "ATE",
                            Nombre = "Disco de Freno Ventilado",
                            Precio = 55.00m,
                            SKU = "ATE-DIS-006",
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 2,
                            CompatibilidadAutos = "Universal - todos los vehículos",
                            Descripcion = "Líquido de frenos DOT4 con alto punto de ebullición para frenado seguro en condiciones extremas.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/liquido-frenos.png",
                            Marca = "Motul",
                            Nombre = "Líquido de Frenos DOT4 500ml",
                            Precio = 9.50m,
                            SKU = "MOT-LIQ-007",
                            Stock = 120
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 3,
                            CompatibilidadAutos = "Nissan Frontier 2005-2021, Toyota Hilux 2005-2021",
                            Descripcion = "Amortiguador de gas de alta presión para conducción suave y estable en todo tipo de terreno.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/amortiguador.png",
                            Marca = "Monroe",
                            Nombre = "Amortiguador Monroe Delantero",
                            Precio = 65.00m,
                            SKU = "MON-AMO-008",
                            Stock = 50
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 3,
                            CompatibilidadAutos = "Ford Focus 2012-2018, Chevrolet Onix 2013-2022",
                            Descripcion = "Rótula de suspensión inferior con grasa de por vida y bota reforzada anti-polvo.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/rotula.png",
                            Marca = "Moog",
                            Nombre = "Rótula Inferior Moog",
                            Precio = 28.00m,
                            SKU = "MOO-ROT-009",
                            Stock = 70
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 4,
                            CompatibilidadAutos = "Universal - vehículos con sistema de 12V",
                            Descripcion = "Batería de arranque libre de mantenimiento con tecnología AGM para alta demanda eléctrica.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/bateria.png",
                            Marca = "Bosch",
                            Nombre = "Batería Bosch 60Ah 12V",
                            Precio = 95.00m,
                            SKU = "BOC-BAT-010",
                            Stock = 35
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 4,
                            CompatibilidadAutos = "Toyota Corolla 2009-2019, Honda Civic 2009-2015",
                            Descripcion = "Alternador remanufacturado de 90 amperios con garantía de 12 meses.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/alternador.png",
                            Marca = "Remy",
                            Nombre = "Alternador Remy 90A",
                            Precio = 120.00m,
                            SKU = "REM-ALT-011",
                            Stock = 20
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaId = 5,
                            CompatibilidadAutos = "Universal - con kit de adaptación incluido",
                            Descripcion = "Filtro de aire lavable y reutilizable que incrementa el flujo de aire hasta 50% vs filtros estándar.",
                            Destacado = true,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/filtro-aire.png",
                            Marca = "K&N",
                            Nombre = "Filtro de Aire K&N",
                            Precio = 55.00m,
                            SKU = "KN-FIL-012",
                            Stock = 45
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaId = 5,
                            CompatibilidadAutos = "Volkswagen Polo 2010-2022, Seat Ibiza 2010-2022",
                            Descripcion = "Filtro de combustible con elemento filtrante de alta capacidad para proteger la bomba de inyección.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/filtro-combustible.png",
                            Marca = "Mann",
                            Nombre = "Filtro de Combustible Mann",
                            Precio = 15.00m,
                            SKU = "MAN-FIL-013",
                            Stock = 90
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaId = 6,
                            CompatibilidadAutos = "Renault Sandero 2013-2022, Dacia Logan 2013-2022",
                            Descripcion = "Kit completo de embrague: disco, plato y rodamiento de empuje. Instalación directa OEM.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/embrague.png",
                            Marca = "LUK",
                            Nombre = "Kit de Embrague LUK",
                            Precio = 185.00m,
                            SKU = "LUK-KIT-014",
                            Stock = 15
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaId = 6,
                            CompatibilidadAutos = "Universal - cajas manuales",
                            Descripcion = "Aceite sintético para cajas de cambio manuales y ejes traseros. API GL-4/GL-5.",
                            Destacado = false,
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagenUrl = "/img/aceite-caja.png",
                            Marca = "Motul",
                            Nombre = "Aceite Caja Manual 75W-90 1L",
                            Precio = 22.00m,
                            SKU = "MOT-CAJ-015",
                            Stock = 85
                        });
                });

            modelBuilder.Entity("EcommerceDemo.Models.OrdenItem", b =>
                {
                    b.HasOne("EcommerceDemo.Models.Orden", "Orden")
                        .WithMany("Items")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("EcommerceDemo.Models.Producto", b =>
                {
                    b.HasOne("EcommerceDemo.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EcommerceDemo.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("EcommerceDemo.Models.Orden", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
